parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: lab
    database_user: lab
    database_password: 7DULcn6NaWdvVxaN

    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null

    locale: en
    secret: 8fb5587e62824ec52fcacd00fc501c5e
