UsersTest:
    type: entity
    table: doctrine_users_test
    id:
        id: 
            type: integer
            generator: 
                strategy: AUTO
    fields:
        username:
            type: string
    oneToMany:
        datas:
            targetEntity: Data
            mappedBy: user
    manyToMany:
        computers:
            targetEntity: Computers
            joinTable:
                name: doctrine_users_computers
                joinColumns:
                    users:
                        referencedColumnName: id
                inverseJoinColumns:
                    computers:
                        referencedColumnName: id
            
