<?php
/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
return function($container) {
    $instance = new \Acme\DemoBundle\Controller\DemoController();
    return $instance;
};
