CREATE TABLE `lab`.`logs` (
`ID` INT NOT NULL AUTO_INCREMENT ,
`time` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL ,
`ip` VARCHAR( 255 ) NOT NULL ,
`link` VARCHAR( 255 ) NOT NULL ,
`description` TEXT NOT NULL ,
PRIMARY KEY ( `ID` ) ,
UNIQUE (
`ID` 
)
) ENGINE = MYISAM ;